== Modellbeschreibung

Gestaltungspläne gemäss Art. 24 PBG sind Teil der Nutzungsplanung und damit wie der Zonenplan
und das Baureglement eigentümerverbindlich. Der Gestaltungsplan verfeinert die Vorgaben der
(Rahmen-)Nutzungsplanung mit zusätzlichen Aussagen über die Nutzung, Erschliessung, Bebauung
und Ausstattung. +

Die Sonderbestimmungen der im ÖREB-Kataster dargestellten Gestaltungspläne werden in der Regel
auf einem oder mehreren (Detail-)Plänen sowie in Vorschriften festgehalten. Im Gegensatz zum
Zonenplan werden die Inhalte der Gestaltungspläne nicht vollständig geometrisch erfasst, sondern –
wie im Geodatenmodell Bereich Nutzungsplanung des Bundes bereits beschrieben – nur der
Planungsperimeter. Die weiteren Planinhalte sind über die im ÖREB-Kataster hinterlegten PDF-Dateien des jeweiligen Gestaltungsplanes zugänglich. Der Perimeter der einzelnen Gestaltungspläne
wird als überlagernder Nutzungsplaninhalt (andere flächenbezogene Festlegungen) erfasst und die
dazugehörigen Dokumente (Plan und Sonderbauvorschriften) im PDF-Format über einen
Dokumentlink mit der entsprechenden Geometrie verknüpft.

=== Zonentypen
[blue]*Todo Tabelle* +

*Ergänzende Information zur Definition des Zonentyps "Bereich rechtsgültiger Gestaltungsplan"* +

Dokumente und Rechtssätze können nur mit Zonentypen und nicht mit einzelnen Geometrien
verknüpft werden. Deshalb braucht es für jeden rechtsgültigen Gestaltungsplan einen eigenen
Zonentyp. Der Code für diesen setzt sich zusammen aus dem kantonalen Typ "61.1" und einer
eindeutigen, laufenden Nummer innerhalb der Gemeinde (z. B. "1", der Code lautet dann z. B.
61.1.1). + 

Die Abkürzung ist stets "rGP". Die Bezeichnung soll anstelle von "Bereich rechtsgültiger
Gestaltungsplan" den Namen des Gestaltungsplans enthalten, vgl. Beispiele in nachfolgender Liste. +

Beispiele für die Definition von Bereichen rechtsgültiger Gestaltungspläne:
[blue]*Todo Tabelle* +
